#!/bin/bash

MODULE_NAME="helpers"
BUILD_TYPE=$1

if ! [ "$BUILD_TYPE" == "Debug" ] && ! [ "$BUILD_TYPE" == "Release" ];
then
    echo "ERROR: A build type, Debug or Release, must be provided."
    echo ""
    exit 1
fi

./gradlew :$MODULE_NAME:assemble$BUILD_TYPE

