#!/bin/bash

APK_CACHE_DIR=$HOME/__APK_INSTALLER

if ! [ -d "$APK_CACHE_DIR" ];
then
    mkdir -p $APK_CACHE_DIR
fi

APK_PATH=$1

if [ "$APK_PATH" == "" ];
then
    echo "Calls TermuxAPI for installing an APK file."
    echo ""
    echo "The APK is first copied to a temporary directory in the"
    echo "internal storage, because the installation may fail if"
    echo "we try to install an APK located in external SD card."
    echo ""
    echo "Usage: install_apk <apk path>"
    echo ""
    exit 1
fi


if ! [ -f "$APK_PATH" ];
then
    echo "ERROR: '$APK_PATH' do not exist."
    echo ""
    exit 1
fi

APK_FILE=$(basename $APK_PATH)
CACHED_APK=$APK_CACHE_DIR/$APK_FILE

cp $APK_PATH $CACHED_APK

echo "Telling Termux to install '$APK_PATH'..."
termux-open --view --content-type "application/vnd.android.package-archive" $CACHED_APK


